### ISSUE TITLE
JavaScript enqueue issue

### ISSUE THREAD

**Issue by dishitpala** [rtCamp/rt-scripts-optimizer#3]
Hello Team,

Please check the below mentioned issues:

https://github.com/rtCamp/rt-scripts-optimizer/blob/main/rt-scripts-optimizer.php#L48-L52
If `amp_is_request` function does not exist then script inside the condition will not get enqueued, update the condition accordingly.

https://github.com/rtCamp/rt-scripts-optimizer/blob/main/rt-scripts-optimizer.php#L69-L71
@pradeep910  Please conform the above condition, because in case of AMP no JS will be enqueued.

Thanks

**Comment by Pradeep1308** [comment]
> Hello Team,
> 
> Please check the below mentioned issues:
> 
> https://github.com/rtCamp/rt-scripts-optimizer/blob/main/rt-scripts-optimizer.php#L48-L52 If `amp_is_request` function does not exist then script inside the condition will not get enqueued, update the condition accordingly.
> 
> https://github.com/rtCamp/rt-scripts-optimizer/blob/main/rt-scripts-optimizer.php#L69-L71 @Pradeep1308 Please conform the above condition, because in case of AMP no JS will be enqueued.
> 
> Thanks

Hi @dishitpala you mentioned wrong Pradeep by mistake.
